# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Talking' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Talking
   pod 'SDiPhoneVersion', '~> 1.1.2'
   pod 'AFNetworking', '~> 3.1.0'
end

